version: "3.7"  # Docker Compose file format v3.7 is when the `init` command was added
services:
    cff_web:
        depends_on:
            - cff_db
        ports:
            # port 3000 is the default port for the Catalyst development server
            - "3000:3000"  # change the first 3000 if it conflicts locally
        image: wbraswell/cloudforfree_catalyst
        init: true
        environment:
            DBPASSWORD: cca43b7b5f364664b3ae4c2ab0e077c4
            DOMAIN: localhost:3000  # configure the domain in the shinycms.conf file
        volumes:
            # mount the base directory of your local CloudForFree git clone inside the running Docker container;
            # this allows you to edit the CloudForFree source code in your local git directory, and the changes will appear inside Docker
            - "../:/home/cloudforfree_user/public_html/cloudforfree.org"

    cff_db:
        ports:
            # no host port is specified on the following line,
            # so Docker Compose binds to a random unused port on the host and forwards it to the internal MySQL port number
            - "3306"  
        image: wbraswell/cloudforfree_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 5f08f597ba64c94e8297a5b2f0d740af
            MYSQL_USER: cloudff_user
            MYSQL_PASSWORD: cca43b7b5f364664b3ae4c2ab0e077c4
            MYSQL_DATABASE: cloudforfree_org
